spring.datasource.url=${DB_URL:${JDBC_DATABASE_URL:${MYSQL_URL:jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:sahakarinet}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}}}
spring.datasource.username=${DB_USER:${JDBC_DATABASE_USERNAME:${MYSQLUSER:root}}}
spring.datasource.password=${DB_PASSWORD:${JDBC_DATABASE_PASSWORD:${MYSQLPASSWORD:12345}}}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true