/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.9
 * Generated at: 2026-04-22 05:36:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>SahakariNet - Digital Cooperative Management</title>\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --bg: #f8fafc;\n");
      out.write("            --text: #0f172a;\n");
      out.write("            --muted: #64748b;\n");
      out.write("            --line: rgba(148, 163, 184, 0.2);\n");
      out.write("            --blue: #2563eb;\n");
      out.write("            --blue-strong: #1d4ed8;\n");
      out.write("            --blue-soft: #dbeafe;\n");
      out.write("            --panel: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        html { scroll-behavior: smooth; }\n");
      out.write("        body {\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            background:\n");
      out.write("                radial-gradient(circle at top left, rgba(37, 99, 235, 0.08), transparent 28%),\n");
      out.write("                linear-gradient(180deg, #ffffff 0%, #f8fbff 36%, #eef4ff 36%, #eef4ff 66%, #ffffff 66%, #ffffff 100%);\n");
      out.write("            color: var(--text);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container-wide { max-width: 1180px; }\n");
      out.write("\n");
      out.write("        .glass-border {\n");
      out.write("            border: 1px solid rgba(37, 99, 235, 0.12);\n");
      out.write("            box-shadow: 0 18px 50px rgba(15, 23, 42, 0.08);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .soft-panel {\n");
      out.write("            background: rgba(255, 255, 255, 0.7);\n");
      out.write("            backdrop-filter: blur(18px);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.65);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-shadow {\n");
      out.write("            box-shadow: 0 28px 60px rgba(15, 23, 42, 0.14);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-hover {\n");
      out.write("            transition: transform 180ms ease, box-shadow 180ms ease, border-color 180ms ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-hover:hover {\n");
      out.write("            transform: translateY(-4px);\n");
      out.write("            box-shadow: 0 24px 45px rgba(15, 23, 42, 0.08);\n");
      out.write("            border-color: rgba(37, 99, 235, 0.18);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-title {\n");
      out.write("            letter-spacing: -0.04em;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body class=\"min-h-screen text-slate-900\">\n");
      out.write("<header class=\"sticky top-0 z-50 bg-white/90 backdrop-blur-xl border-b border-slate-200/70\">\n");
      out.write("    <div class=\"container-wide mx-auto px-5 lg:px-8 h-16 flex items-center justify-between\">\n");
      out.write("        <a href=\"index.jsp\" class=\"flex items-center gap-2.5 font-extrabold text-slate-900\">\n");
      out.write("            <span class=\"w-7 h-7 rounded-lg bg-blue-600 text-white flex items-center justify-center shadow-sm\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" class=\"w-4 h-4\" stroke=\"currentColor\" stroke-width=\"2\" aria-hidden=\"true\">\n");
      out.write("                    <path d=\"M4 12.5 12 5l8 7.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n");
      out.write("                    <path d=\"M6.5 10.5V19h11V10.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n");
      out.write("                </svg>\n");
      out.write("            </span>\n");
      out.write("            <span class=\"tracking-tight\">Sahakari<span class=\"text-blue-600\">Net</span></span>\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("        <nav class=\"hidden md:flex items-center gap-8 text-sm text-slate-500\">\n");
      out.write("            <a href=\"#features\" class=\"hover:text-slate-900 transition\">Features</a>\n");
      out.write("            <a href=\"#dashboards\" class=\"hover:text-slate-900 transition\">Dashboards</a>\n");
      out.write("            <a href=\"about.jsp\" class=\"hover:text-slate-900 transition\">About</a>\n");
      out.write("            <a href=\"contact.jsp\" class=\"hover:text-slate-900 transition\">Contact</a>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <div class=\"flex items-center gap-3 text-sm\">\n");
      out.write("            <a href=\"login.jsp\" class=\"px-3.5 py-2 text-slate-700 hover:text-slate-900 transition\">Log in</a>\n");
      out.write("            <a href=\"register.jsp\" class=\"px-4 py-2.5 rounded-lg bg-blue-600 text-white font-semibold hover:bg-blue-700 transition shadow-sm shadow-blue-200\">\n");
      out.write("                Register\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<main>\n");
      out.write("    <section class=\"px-5 lg:px-8 pt-16 pb-20 lg:pt-24 lg:pb-28\">\n");
      out.write("        <div class=\"container-wide mx-auto grid lg:grid-cols-2 gap-12 lg:gap-16 items-center\">\n");
      out.write("            <div class=\"max-w-xl\">\n");
      out.write("                <div class=\"inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-50 border border-blue-100 text-blue-700 text-xs font-semibold mb-6\">\n");
      out.write("                    <span class=\"w-2 h-2 rounded-full bg-blue-500\"></span>\n");
      out.write("                    Empowering Nepal's Cooperatives\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <h1 class=\"section-title text-4xl sm:text-5xl lg:text-6xl font-black leading-[1.02] tracking-tight text-slate-950\">\n");
      out.write("                    Digitize Your\n");
      out.write("                    Cooperative\n");
      out.write("                    Management\n");
      out.write("                </h1>\n");
      out.write("\n");
      out.write("                <p class=\"mt-6 text-base sm:text-lg leading-8 text-slate-500 max-w-lg\">\n");
      out.write("                    Move beyond manual ledgers. SahakariNet brings efficiency, transparency, and security to your daily financial operations with a complete web-based system.\n");
      out.write("                </p>\n");
      out.write("\n");
      out.write("                <div class=\"flex flex-wrap gap-3 mt-8\">\n");
      out.write("                    <a href=\"register.jsp\" class=\"inline-flex items-center justify-center gap-2 px-5 py-3 rounded-lg bg-blue-600 text-white font-semibold shadow-sm shadow-blue-200 hover:bg-blue-700 transition\">\n");
      out.write("                        Get Started Today\n");
      out.write("                        <svg viewBox=\"0 0 20 20\" fill=\"currentColor\" class=\"w-4 h-4\" aria-hidden=\"true\"><path fill-rule=\"evenodd\" d=\"M7.47 4.47a.75.75 0 011.06 0l5 5a.75.75 0 010 1.06l-5 5a.75.75 0 11-1.06-1.06L11.94 10 7.47 5.53a.75.75 0 010-1.06z\" clip-rule=\"evenodd\"/></svg>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"#features\" class=\"inline-flex items-center justify-center px-5 py-3 rounded-lg bg-white border border-slate-200 text-slate-700 font-medium hover:border-slate-300 hover:bg-slate-50 transition\">\n");
      out.write("                        Learn More\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"relative\">\n");
      out.write("                <div class=\"absolute -inset-3 rounded-[28px] bg-gradient-to-br from-blue-200/30 via-transparent to-blue-500/30 blur-2xl\"></div>\n");
      out.write("                <div class=\"relative soft-panel glass-border rounded-[22px] p-4 sm:p-5 lg:p-6 hero-shadow\">\n");
      out.write("                    <div class=\"relative overflow-hidden rounded-[18px] bg-gradient-to-br from-blue-50 via-white to-blue-300/80 p-4 sm:p-5 lg:p-6 min-h-[320px] flex items-center justify-center\">\n");
      out.write("                        <div class=\"absolute inset-x-0 top-0 h-10 bg-gradient-to-r from-blue-700 via-blue-600 to-blue-500 rounded-t-[18px]\"></div>\n");
      out.write("\n");
      out.write("                        <div class=\"relative w-full max-w-[470px] rounded-[14px] bg-slate-950/90 p-3 shadow-2xl shadow-slate-900/20\">\n");
      out.write("                            <div class=\"rounded-[10px] bg-slate-100 overflow-hidden\">\n");
      out.write("                                <div class=\"h-5 bg-blue-600/95 flex items-center gap-1.5 px-2.5\">\n");
      out.write("                                    <span class=\"w-1.5 h-1.5 rounded-full bg-white/90\"></span>\n");
      out.write("                                    <span class=\"w-1.5 h-1.5 rounded-full bg-white/70\"></span>\n");
      out.write("                                    <span class=\"w-1.5 h-1.5 rounded-full bg-white/50\"></span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"p-3 sm:p-4 bg-slate-50\">\n");
      out.write("                                    <div class=\"grid grid-cols-[120px_1fr] gap-3 items-start\">\n");
      out.write("                                        <aside class=\"rounded-xl bg-blue-100/70 p-3\">\n");
      out.write("                                            <div class=\"space-y-2\">\n");
      out.write("                                                <div class=\"h-2.5 w-16 rounded-full bg-blue-200\"></div>\n");
      out.write("                                                <div class=\"h-2.5 w-20 rounded-full bg-blue-200\"></div>\n");
      out.write("                                                <div class=\"h-2.5 w-12 rounded-full bg-blue-300\"></div>\n");
      out.write("                                                <div class=\"mt-3 h-16 rounded-xl bg-white border border-blue-100\"></div>\n");
      out.write("                                                <div class=\"h-12 rounded-xl bg-white border border-blue-100\"></div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </aside>\n");
      out.write("\n");
      out.write("                                        <section class=\"space-y-3\">\n");
      out.write("                                            <div class=\"flex items-center justify-between\">\n");
      out.write("                                                <div>\n");
      out.write("                                                    <div class=\"h-3 w-20 rounded-full bg-slate-200 mb-2\"></div>\n");
      out.write("                                                    <div class=\"h-5 w-28 rounded-full bg-slate-300\"></div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"h-8 w-8 rounded-full bg-blue-200\"></div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"grid grid-cols-3 gap-3\">\n");
      out.write("                                                <div class=\"rounded-xl bg-white border border-slate-100 p-3 shadow-sm\">\n");
      out.write("                                                    <div class=\"h-2.5 w-14 rounded-full bg-slate-200 mb-3\"></div>\n");
      out.write("                                                    <div class=\"h-5 w-16 rounded-full bg-blue-200\"></div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"rounded-xl bg-white border border-slate-100 p-3 shadow-sm\">\n");
      out.write("                                                    <div class=\"h-2.5 w-12 rounded-full bg-slate-200 mb-3\"></div>\n");
      out.write("                                                    <div class=\"h-5 w-20 rounded-full bg-blue-200\"></div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"rounded-xl bg-white border border-slate-100 p-3 shadow-sm\">\n");
      out.write("                                                    <div class=\"h-2.5 w-10 rounded-full bg-slate-200 mb-3\"></div>\n");
      out.write("                                                    <div class=\"h-5 w-14 rounded-full bg-blue-200\"></div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"grid grid-cols-2 gap-3\">\n");
      out.write("                                                <div class=\"rounded-2xl bg-white border border-slate-100 p-3 h-40 shadow-sm\">\n");
      out.write("                                                    <div class=\"h-3 w-24 rounded-full bg-slate-200 mb-4\"></div>\n");
      out.write("                                                    <div class=\"flex items-end gap-2 h-24 pt-10\">\n");
      out.write("                                                        <span class=\"w-3 bg-blue-200 rounded-t-md h-10\"></span>\n");
      out.write("                                                        <span class=\"w-3 bg-blue-300 rounded-t-md h-16\"></span>\n");
      out.write("                                                        <span class=\"w-3 bg-blue-400 rounded-t-md h-12\"></span>\n");
      out.write("                                                        <span class=\"w-3 bg-blue-500 rounded-t-md h-20\"></span>\n");
      out.write("                                                        <span class=\"w-3 bg-blue-300 rounded-t-md h-14\"></span>\n");
      out.write("                                                        <span class=\"w-3 bg-blue-400 rounded-t-md h-24\"></span>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"rounded-2xl bg-white border border-slate-100 p-3 h-40 shadow-sm flex flex-col\">\n");
      out.write("                                                    <div class=\"h-3 w-24 rounded-full bg-slate-200 mb-4\"></div>\n");
      out.write("                                                    <div class=\"flex-1 flex items-center justify-center\">\n");
      out.write("                                                        <div class=\"w-28 h-28 rounded-full border-[14px] border-blue-500/20 border-r-blue-600 border-b-blue-600\"></div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </section>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section id=\"features\" class=\"px-5 lg:px-8 py-20 bg-[#eaf2ff]\">\n");
      out.write("        <div class=\"container-wide mx-auto\">\n");
      out.write("            <div class=\"max-w-3xl mx-auto text-center mb-14\">\n");
      out.write("                <h2 class=\"section-title text-3xl sm:text-4xl font-extrabold text-slate-900\">Built for Modern Cooperatives</h2>\n");
      out.write("                <p class=\"mt-4 text-slate-500 leading-7\">\n");
      out.write("                    Everything you need to run your cooperative efficiently, securely, and transparently in one unified MVC architecture platform.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"grid sm:grid-cols-2 lg:grid-cols-3 gap-5 lg:gap-6\">\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-6\">\n");
      out.write("                    <div class=\"w-10 h-10 rounded-xl bg-blue-50 mb-5\"></div>\n");
      out.write("                    <h3 class=\"font-semibold text-lg text-slate-900\">Secure & Transparent</h3>\n");
      out.write("                    <p class=\"mt-3 text-sm leading-6 text-slate-500\">Encrypted passwords, secure user sessions, and a comprehensive audit trail build trust among your members and reduce fraud risks.</p>\n");
      out.write("                </article>\n");
      out.write("\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-6\">\n");
      out.write("                    <div class=\"w-10 h-10 rounded-xl bg-blue-50 mb-5\"></div>\n");
      out.write("                    <h3 class=\"font-semibold text-lg text-slate-900\">Automated Calculations</h3>\n");
      out.write("                    <p class=\"mt-3 text-sm leading-6 text-slate-500\">The system automatically calculates complex interest rates on savings and loans, eliminating manual errors and saving valuable staff time.</p>\n");
      out.write("                </article>\n");
      out.write("\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-6\">\n");
      out.write("                    <div class=\"w-10 h-10 rounded-xl bg-blue-50 mb-5\"></div>\n");
      out.write("                    <h3 class=\"font-semibold text-lg text-slate-900\">Digital Loan Processing</h3>\n");
      out.write("                    <p class=\"mt-3 text-sm leading-6 text-slate-500\">Manage the entire loan lifecycle from member application submission to admin approval, fund disbursement, and repayment tracking.</p>\n");
      out.write("                </article>\n");
      out.write("\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-6\">\n");
      out.write("                    <div class=\"w-10 h-10 rounded-xl bg-blue-50 mb-5\"></div>\n");
      out.write("                    <h3 class=\"font-semibold text-lg text-slate-900\">Real-Time Reporting</h3>\n");
      out.write("                    <p class=\"mt-3 text-sm leading-6 text-slate-500\">Generate accurate reports for auditing instantly. View monthly savings totals, loan recovery rates, and track defaulters easily.</p>\n");
      out.write("                </article>\n");
      out.write("\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-6\">\n");
      out.write("                    <div class=\"w-10 h-10 rounded-xl bg-blue-50 mb-5\"></div>\n");
      out.write("                    <h3 class=\"font-semibold text-lg text-slate-900\">Member Management</h3>\n");
      out.write("                    <p class=\"mt-3 text-sm leading-6 text-slate-500\">Streamline registrations with automated approval workflows. Maintain complete digital profiles including citizenship details and history.</p>\n");
      out.write("                </article>\n");
      out.write("\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-6\">\n");
      out.write("                    <div class=\"w-10 h-10 rounded-xl bg-blue-50 mb-5\"></div>\n");
      out.write("                    <h3 class=\"font-semibold text-lg text-slate-900\">Complete History</h3>\n");
      out.write("                    <p class=\"mt-3 text-sm leading-6 text-slate-500\">Access full transaction histories across the cooperative or search specific member records by name, phone, or citizenship number.</p>\n");
      out.write("                </article>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section id=\"dashboards\" class=\"px-5 lg:px-8 py-24 bg-white\">\n");
      out.write("        <div class=\"container-wide mx-auto\">\n");
      out.write("            <div class=\"max-w-3xl mx-auto text-center mb-14\">\n");
      out.write("                <h2 class=\"section-title text-3xl sm:text-4xl font-extrabold text-slate-900\">Tailored Dashboards for Every Role</h2>\n");
      out.write("                <p class=\"mt-4 text-slate-500 leading-7\">\n");
      out.write("                    SahakariNet implements strict role-based access control, providing specific tools and views based on administrative responsibilities.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"grid lg:grid-cols-3 gap-5 lg:gap-6\">\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-7\">\n");
      out.write("                    <div class=\"flex items-center gap-3 mb-6\">\n");
      out.write("                        <div class=\"w-12 h-12 rounded-xl bg-blue-50\"></div>\n");
      out.write("                        <h3 class=\"text-xl font-semibold text-slate-900\">Admin View</h3>\n");
      out.write("                    </div>\n");
      out.write("                    <ul class=\"space-y-3 text-sm leading-6 text-slate-500\">\n");
      out.write("                        <li>Approve or reject member registrations</li>\n");
      out.write("                        <li>Review and approve loan applications</li>\n");
      out.write("                        <li>View loan defaulter lists instantly</li>\n");
      out.write("                        <li>Generate comprehensive financial reports</li>\n");
      out.write("                        <li>Manage staff accounts and permissions</li>\n");
      out.write("                    </ul>\n");
      out.write("                </article>\n");
      out.write("\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-7\">\n");
      out.write("                    <div class=\"flex items-center gap-3 mb-6\">\n");
      out.write("                        <div class=\"w-12 h-12 rounded-xl bg-emerald-50\"></div>\n");
      out.write("                        <h3 class=\"text-xl font-semibold text-slate-900\">Staff View</h3>\n");
      out.write("                    </div>\n");
      out.write("                    <ul class=\"space-y-3 text-sm leading-6 text-slate-500\">\n");
      out.write("                        <li>Record member deposits and withdrawals</li>\n");
      out.write("                        <li>Process approved loan disbursements</li>\n");
      out.write("                        <li>Record loan repayments from members</li>\n");
      out.write("                        <li>Search member records efficiently</li>\n");
      out.write("                        <li>View automated interest calculations</li>\n");
      out.write("                    </ul>\n");
      out.write("                </article>\n");
      out.write("\n");
      out.write("                <article class=\"card-hover bg-white rounded-2xl border border-slate-200 p-7\">\n");
      out.write("                    <div class=\"flex items-center gap-3 mb-6\">\n");
      out.write("                        <div class=\"w-12 h-12 rounded-xl bg-violet-50\"></div>\n");
      out.write("                        <h3 class=\"text-xl font-semibold text-slate-900\">Member View</h3>\n");
      out.write("                    </div>\n");
      out.write("                    <ul class=\"space-y-3 text-sm leading-6 text-slate-500\">\n");
      out.write("                        <li>View personal savings balance and shares</li>\n");
      out.write("                        <li>Submit loan applications directly online</li>\n");
      out.write("                        <li>View detailed loan repayment schedules</li>\n");
      out.write("                        <li>Track personal transaction history</li>\n");
      out.write("                        <li>Update personal profile details securely</li>\n");
      out.write("                    </ul>\n");
      out.write("                </article>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section class=\"px-5 lg:px-8 py-20 bg-blue-600 text-white\">\n");
      out.write("        <div class=\"container-wide mx-auto text-center max-w-3xl\">\n");
      out.write("            <h2 class=\"section-title text-3xl sm:text-4xl font-extrabold tracking-tight\">Ready to Transform Your Cooperative?</h2>\n");
      out.write("            <p class=\"mt-5 text-blue-100 leading-7\">\n");
      out.write("                Join the movement towards digital empowerment in Nepal's cooperative sector. Reduce manual errors, build trust, and save time with SahakariNet.\n");
      out.write("            </p>\n");
      out.write("            <div class=\"flex flex-wrap justify-center gap-3 mt-8\">\n");
      out.write("                <a href=\"register.jsp\" class=\"px-5 py-3 rounded-lg bg-white text-blue-700 font-semibold hover:bg-blue-50 transition\">\n");
      out.write("                    Register Now\n");
      out.write("                </a>\n");
      out.write("                <a href=\"contact.jsp\" class=\"px-5 py-3 rounded-lg border border-white/30 bg-white/5 text-white font-medium hover:bg-white/10 transition\">\n");
      out.write("                    Contact Sales\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<footer class=\"bg-slate-950 text-slate-300\">\n");
      out.write("    <div class=\"container-wide mx-auto px-5 lg:px-8 py-14 lg:py-16 grid sm:grid-cols-2 lg:grid-cols-4 gap-10\">\n");
      out.write("        <div>\n");
      out.write("            <div class=\"flex items-center gap-2.5 font-extrabold text-white\">\n");
      out.write("                <span class=\"w-8 h-8 rounded-lg bg-white text-slate-950 flex items-center justify-center\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" class=\"w-4 h-4\" stroke=\"currentColor\" stroke-width=\"2\" aria-hidden=\"true\">\n");
      out.write("                        <path d=\"M4 12.5 12 5l8 7.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n");
      out.write("                        <path d=\"M6.5 10.5V19h11V10.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n");
      out.write("                    </svg>\n");
      out.write("                </span>\n");
      out.write("                <span>SahakariNet</span>\n");
      out.write("            </div>\n");
      out.write("            <p class=\"mt-4 text-sm leading-7 text-slate-400 max-w-xs\">\n");
      out.write("                Empowering Nepal's cooperative sector with secure, digital, and efficient web-based management tools.\n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("            <h3 class=\"text-white font-semibold mb-4\">Platform</h3>\n");
      out.write("            <ul class=\"space-y-3 text-sm text-slate-400\">\n");
      out.write("                <li><a href=\"#features\" class=\"hover:text-white transition\">Features</a></li>\n");
      out.write("                <li><a href=\"#dashboards\" class=\"hover:text-white transition\">Role Access</a></li>\n");
      out.write("                <li><a href=\"#\" class=\"hover:text-white transition\">Security & Privacy</a></li>\n");
      out.write("                <li><a href=\"#\" class=\"hover:text-white transition\">System Requirements</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("            <h3 class=\"text-white font-semibold mb-4\">Company</h3>\n");
      out.write("            <ul class=\"space-y-3 text-sm text-slate-400\">\n");
      out.write("                <li><a href=\"about.jsp\" class=\"hover:text-white transition\">About Us</a></li>\n");
      out.write("                <li><a href=\"#\" class=\"hover:text-white transition\">Success Stories</a></li>\n");
      out.write("                <li><a href=\"#\" class=\"hover:text-white transition\">News & Updates</a></li>\n");
      out.write("                <li><a href=\"contact.jsp\" class=\"hover:text-white transition\">Contact Us</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("            <h3 class=\"text-white font-semibold mb-4\">Support</h3>\n");
      out.write("            <ul class=\"space-y-3 text-sm text-slate-400\">\n");
      out.write("                <li><a href=\"#\" class=\"hover:text-white transition\">Help Center</a></li>\n");
      out.write("                <li><a href=\"#\" class=\"hover:text-white transition\">Documentation</a></li>\n");
      out.write("                <li><a href=\"#\" class=\"hover:text-white transition\">Terms of Service</a></li>\n");
      out.write("                <li><a href=\"#\" class=\"hover:text-white transition\">Privacy Policy</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"border-t border-white/10\">\n");
      out.write("        <div class=\"container-wide mx-auto px-5 lg:px-8 py-5 text-xs text-slate-500\">\n");
      out.write("            © 2026 SahakariNet. Built for Nepal's cooperative community.\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
