/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.9
 * Generated at: 2026-04-22 07:10:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login — SahakariNet</title>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Plus Jakarta Sans', sans-serif;\r\n");
      out.write("            background: #F1F5F9;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"min-h-screen flex items-center justify-center px-4\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"w-full max-w-6xl bg-white rounded-[32px] shadow-[0_25px_60px_rgba(0,0,0,0.08)] overflow-hidden flex flex-col md:flex-row\">\r\n");
      out.write("\r\n");
      out.write("    <!-- LEFT SIDE -->\r\n");
      out.write("    <div class=\"w-full md:w-2/5 bg-[#EEF4FF] p-12 flex flex-col justify-between\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Logo + Text -->\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"flex items-center gap-3 mb-6\">\r\n");
      out.write("                <div class=\"w-11 h-11 bg-blue-600 rounded-xl flex items-center justify-center text-white font-bold text-lg\">S</div>\r\n");
      out.write("                <h1 class=\"text-2xl font-extrabold text-gray-900\">\r\n");
      out.write("                    Sahakari<span class=\"text-blue-600\">Net</span>\r\n");
      out.write("                </h1>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"text-gray-600 text-sm leading-relaxed\">\r\n");
      out.write("                A secure academic project interface for managing members, savings, loans, reports, and cooperative operations with clarity.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Stats Card -->\r\n");
      out.write("        <div class=\"bg-white rounded-2xl p-6 shadow-sm border border-gray-100 mt-10\">\r\n");
      out.write("            <p class=\"text-[10px] font-semibold text-gray-400 uppercase tracking-widest mb-2\">\r\n");
      out.write("                Built for Nepal's cooperative sector\r\n");
      out.write("            </p>\r\n");
      out.write("            <h2 class=\"text-4xl font-extrabold text-gray-900 mb-2\">34,000+</h2>\r\n");
      out.write("            <p class=\"text-sm text-gray-500\">\r\n");
      out.write("                Community cooperatives can move from paper-based records to a cleaner and more transparent digital workflow.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Features -->\r\n");
      out.write("        <div class=\"mt-10 space-y-4 text-sm text-gray-600\">\r\n");
      out.write("            <div class=\"flex items-start gap-3\">\r\n");
      out.write("                <div class=\"w-8 h-8 bg-blue-100 text-blue-600 flex items-center justify-center rounded-lg\">✓</div>\r\n");
      out.write("                <p>Role-based access for admin, staff, and members</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex items-start gap-3\">\r\n");
      out.write("                <div class=\"w-8 h-8 bg-blue-100 text-blue-600 flex items-center justify-center rounded-lg\">✓</div>\r\n");
      out.write("                <p>Reliable savings, loan, and repayment management</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex items-start gap-3\">\r\n");
      out.write("                <div class=\"w-8 h-8 bg-blue-100 text-blue-600 flex items-center justify-center rounded-lg\">✓</div>\r\n");
      out.write("                <p>Clear reports for operations, auditing, and trust</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- RIGHT SIDE -->\r\n");
      out.write("    <div class=\"w-full md:w-3/5 p-10 md:p-16 flex flex-col justify-center\">\r\n");
      out.write("\r\n");
      out.write("        ");
 if ("true".equals(request.getParameter("logout"))) { 
      out.write("\r\n");
      out.write("        <div class=\"bg-green-50 border border-green-200 text-green-700 text-sm px-4 py-3 rounded-xl mb-6 flex items-center gap-2\">\r\n");
      out.write("            ✓ You have been logged out successfully.\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h2 class=\"text-3xl font-extrabold text-gray-900 mb-2\">Welcome back</h2>\r\n");
      out.write("        <p class=\"text-gray-500 text-sm mb-8\">\r\n");
      out.write("            Sign in to continue to your cooperative dashboard.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"login\" method=\"post\" class=\"space-y-5\">\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <label class=\"block text-xs font-semibold text-gray-600 uppercase mb-2\">Username</label>\r\n");
      out.write("                <input type=\"text\" name=\"username\" placeholder=\"Enter your username\" required\r\n");
      out.write("                       class=\"w-full border border-gray-200 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <label class=\"block text-xs font-semibold text-gray-600 uppercase mb-2\">Password</label>\r\n");
      out.write("                <input type=\"password\" name=\"password\" placeholder=\"Enter your password\" required\r\n");
      out.write("                       class=\"w-full border border-gray-200 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"text-right mt-2\">\r\n");
      out.write("                    <a href=\"forgot-password\" class=\"text-xs text-blue-600 font-semibold hover:underline\">\r\n");
      out.write("                        Forgot password?\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\"\r\n");
      out.write("                    class=\"w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3.5 rounded-xl text-sm transition\">\r\n");
      out.write("                Sign In →\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"text-center text-sm text-gray-500 mt-6\">\r\n");
      out.write("            Don't have an account?\r\n");
      out.write("            <a href=\"register.jsp\" class=\"text-blue-600 font-semibold hover:underline\">\r\n");
      out.write("                Register here\r\n");
      out.write("            </a>\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"text-center mt-8\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-xs text-gray-400 hover:text-gray-600 underline\">\r\n");
      out.write("                ← Back to home\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
