/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.9
 * Generated at: 2026-04-22 05:33:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String error = (String) request.getAttribute("error");
    String success = request.getParameter("success");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Register — SahakariNet</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("    font-family:'Plus Jakarta Sans',sans-serif;\r\n");
      out.write("    background:#F1F5F9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Typography tuning */\r\n");
      out.write(".title-main{\r\n");
      out.write("    font-size:30px;\r\n");
      out.write("    font-weight:800;\r\n");
      out.write("    color:#0F172A;\r\n");
      out.write("}\r\n");
      out.write(".section-title{\r\n");
      out.write("    font-size:12px;\r\n");
      out.write("    font-weight:700;\r\n");
      out.write("    letter-spacing:0.08em;\r\n");
      out.write("    color:#94A3B8;\r\n");
      out.write("    text-transform:uppercase;\r\n");
      out.write("}\r\n");
      out.write(".input-text{\r\n");
      out.write("    font-size:14px;\r\n");
      out.write("    font-weight:500;\r\n");
      out.write("    color:#0F172A;\r\n");
      out.write("}\r\n");
      out.write("input::placeholder{\r\n");
      out.write("    color:#94A3B8;\r\n");
      out.write("    font-weight:500;\r\n");
      out.write("}\r\n");
      out.write(".desc{\r\n");
      out.write("    font-size:14px;\r\n");
      out.write("    color:#64748B;\r\n");
      out.write("}\r\n");
      out.write(".btn{\r\n");
      out.write("    font-size:15px;\r\n");
      out.write("    font-weight:600;\r\n");
      out.write("}\r\n");
      out.write(".small-text{\r\n");
      out.write("    font-size:13px;\r\n");
      out.write("    color:#94A3B8;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"min-h-screen p-4 md:p-12\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-start\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- LEFT -->\r\n");
      out.write("    <div class=\"space-y-8\">\r\n");
      out.write("        <div class=\"flex items-center gap-3\">\r\n");
      out.write("            <div class=\"w-10 h-10 bg-[#3B82F6] rounded-xl flex items-center justify-center text-white font-bold text-lg shadow-lg\">S</div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1 class=\"text-2xl font-extrabold text-gray-900\">\r\n");
      out.write("                    Sahakari<span class=\"text-blue-600\">Net</span>\r\n");
      out.write("                </h1>\r\n");
      out.write("                <p class=\"text-[11px] text-gray-400 uppercase tracking-widest font-semibold\">\r\n");
      out.write("                    Cooperative management platform\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <p class=\"desc leading-relaxed\">\r\n");
      out.write("            Create your member account for Nepal's cooperative management system with a clean, secure, and professional registration experience.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"bg-white p-8 rounded-3xl border border-gray-100 shadow-sm\">\r\n");
      out.write("            <p class=\"section-title mb-2\">Member registration only</p>\r\n");
      out.write("            <h2 class=\"text-2xl font-extrabold text-gray-900 mb-3\">\r\n");
      out.write("                Account activates after admin approval\r\n");
      out.write("            </h2>\r\n");
      out.write("            <p class=\"desc\">\r\n");
      out.write("                Every new registration stays pending until the cooperative admin verifies the details and approves the account for access.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"space-y-6\">\r\n");
      out.write("            <div class=\"flex gap-4\">\r\n");
      out.write("                <div class=\"w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-sm\">1</div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 class=\"font-semibold text-gray-900 text-sm\">\r\n");
      out.write("                        Your application is saved with status PENDING\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <p class=\"small-text mt-1\">\r\n");
      out.write("                        Submit your personal details and account credentials.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"flex gap-4\">\r\n");
      out.write("                <div class=\"w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-sm\">2</div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 class=\"font-semibold text-gray-900 text-sm\">\r\n");
      out.write("                        The cooperative Admin reviews your application\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <p class=\"small-text mt-1\">\r\n");
      out.write("                        Your identity and registration information are checked.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"flex gap-4\">\r\n");
      out.write("                <div class=\"w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-sm\">3</div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 class=\"font-semibold text-gray-900 text-sm\">\r\n");
      out.write("                        Admin approves and your status becomes APPROVED\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <p class=\"small-text mt-1\">\r\n");
      out.write("                        Once approved, your account is activated.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- RIGHT -->\r\n");
      out.write("    <div class=\"bg-white rounded-3xl border border-gray-100 shadow-lg p-8\">\r\n");
      out.write("        <h2 class=\"title-main mb-2\">Create your account</h2>\r\n");
      out.write("        <p class=\"desc mb-8\">\r\n");
      out.write("            Member registration only. Account activates after admin approval.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (error != null) { 
      out.write("\r\n");
      out.write("            <div class=\"mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700\">\r\n");
      out.write("                ");
      out.print( error );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if ("true".equals(success)) { 
      out.write("\r\n");
      out.write("            <div class=\"mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700\">\r\n");
      out.write("                Registration submitted successfully. Your account is pending admin approval.\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <form action=\"register\" method=\"post\" class=\"space-y-5\" onsubmit=\"return validateForm()\">\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h3 class=\"section-title mb-4\">Personal Information</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\r\n");
      out.write("                    <input type=\"text\" name=\"fullName\" placeholder=\"Full Name *\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"date\" name=\"dob\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 text-gray-400 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("\r\n");
      out.write("                    <select name=\"gender\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 text-gray-400 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("                        <option value=\"\" selected disabled>Select gender</option>\r\n");
      out.write("                        <option>Male</option><option>Female</option><option>Other</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"tel\" name=\"phone\" placeholder=\"Phone Number *\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\" name=\"citizenshipNo\" placeholder=\"Citizenship No. *\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 mt-4 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\" name=\"address\" placeholder=\"Address *\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 mt-4 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h3 class=\"section-title mb-4 mt-6\">Login Credentials</h3>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"email\" name=\"email\" placeholder=\"Email\" class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"text\" name=\"username\" placeholder=\"Username *\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 mt-4 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"grid grid-cols-2 gap-4 mt-4\">\r\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Password *\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" placeholder=\"Confirm Password *\" required class=\"input-text w-full border border-gray-200 rounded-xl px-4 py-3 focus:ring-2 focus:ring-blue-500 outline-none\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn w-full bg-[#3B82F6] hover:bg-blue-700 text-white py-4 rounded-xl transition mt-6\">\r\n");
      out.write("                Submit Registration\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"text-center small-text mt-4\">\r\n");
      out.write("                Account will be PENDING until Admin approves.\r\n");
      out.write("                Already registered?\r\n");
      out.write("                <a href=\"login.jsp\" class=\"text-blue-600 font-semibold hover:underline\">Login</a>\r\n");
      out.write("            </p>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validateForm(){\r\n");
      out.write("    const p=document.getElementById('password').value;\r\n");
      out.write("    const c=document.getElementById('confirmPassword').value;\r\n");
      out.write("    if(p!==c){\r\n");
      out.write("        alert(\"Passwords do not match.\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
